// <auto-generated />
using ContactService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace ContactService.Migrations;

[DbContext(typeof(ContactDbContext))]
partial class ContactDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("ContactService.Models.Contact", b =>
        {
            b.Property<int>("ContactId")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

            b.Property<int>("CategoryId").HasColumnType("int");
            b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
            b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");

            b.HasKey("ContactId");
            b.ToTable("Contacts");
        });
#pragma warning restore 612, 618
    }
}
